INSERT INTO t_admin_user (name, password, nickname, email, role_id, is_use, create_date, creator_id, edit_date, editor_id)
VALUES ('admin', 'fEqNCco3Yq9h5ZUglD3CZJT4lBs', 'admin', 'wuyongzhao@duoquyuedu.com', 1, 1, sysdate(), 1, sysdate(), 1);

INSERT INTO t_admin_role (name, memo) VALUES ('管理员', '管理员');
INSERT INTO t_admin_role (name, memo) VALUES ('操作员', '操作员');

INSERT INTO t_admin_menu (text, order_id, parent_id, is_leaf, is_use) VALUES ('权限管理', 5, 0, 0, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('用户管理', 'adminUserList', 5, 1, 1, 1);

INSERT INTO t_admin_menu (text, order_id, parent_id, is_leaf, is_use) VALUES ('资源管理', 10, 0, 0, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('书籍管理', 'bookList', 5, 3, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('书籍推荐管理', 'recommendLogList', 10, 3, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('章节管理', 'chapterList', 10, 3, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('标签管理', 'tagList', 15, 3, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('分类管理', 'categoryList', 20, 3, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('排行管理', 'rankingList', 25, 3, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('书单管理', 'groupList', 30, 3, 1, 0);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('评论管理', 'commentList', 35, 3, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('敏感词管理', 'filterWordList', 40, 3, 1, 1);

INSERT INTO t_admin_menu (text, order_id, parent_id, is_leaf, is_use) VALUES ('版权管理', 15, 0, 0, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('版权方管理', 'providerList', 5, 12, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('批次管理', 'batchList', 10, 12, 1, 1);

INSERT INTO t_admin_menu (text, order_id, parent_id, is_leaf, is_use) VALUES ('组件管理', 20, 0, 0, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('组件类型管理', 'componentTypeList', 5, 15, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('组件管理', 'componentList', 10, 15, 1, 1);

INSERT INTO t_admin_menu (text, order_id, parent_id, is_leaf, is_use) VALUES ('运营管理', 25, 0, 0, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('页面管理', 'containerList', 5, 18, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('升级管理', 'upgradeList', 10, 18, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('PUSH管理', 'pushList', 15, 18, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('书城TAB', 'tabList', 20, 18, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('启动页配置', 'splashList', 25, 18, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('启动入口配置', 'entryList', 30, 18, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('书架资源配置', 'bookshelfList', 35, 18, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('个人中心推荐', 'userRecommendList', 40, 18, 1, 1);

INSERT INTO t_admin_menu (text, order_id, parent_id, is_leaf, is_use) VALUES ('广告管理', 30, 0, 0, 0);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('书架广告', 'bookshelfAdvList', 5, 26, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('固定间隔广告', 'fixedIntervalsAdvList', 10, 26, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('固定章节广告', 'fixedChapterAdvList', 10, 26, 1, 1);

INSERT INTO t_admin_menu (text, order_id, parent_id, is_leaf, is_use) VALUES ('用户管理', 35, 0, 0, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('用户管理', 'userList', 5, 30, 1, 1);
INSERT INTO t_admin_menu (text, url, order_id, parent_id, is_leaf, is_use) VALUES ('反馈管理', 'feedbackList', 10, 30, 1, 1);


insert into t_platform (id,name,create_date,creator_id,edit_date,editor_id,is_use) values(1,'Android',sysdate(),1,sysdate(),1,1);
insert into t_platform (id,name,create_date,creator_id,edit_date,editor_id,is_use) values(2,'360阅读插件',sysdate(),1,sysdate(),1,1);

insert into t_provider (name, status, create_date, creator_id, edit_date, editor_id) values ('起点', 0, sysdate(), 1, sysdate(), 1);
insert into t_provider (name, status, create_date, creator_id, edit_date, editor_id) values ('岳麓', 1, sysdate(), 1, sysdate(), 1);
insert into t_provider (name, status, create_date, creator_id, edit_date, editor_id) values ('一千零一页', 1, sysdate(), 1, sysdate(), 1);
insert into t_provider (name, status, create_date, creator_id, edit_date, editor_id) values ('纵横', 1, sysdate(), 1, sysdate(), 1);
insert into t_provider (name, status, create_date, creator_id, edit_date, editor_id) values ('看书网', 1, sysdate(), 1, sysdate(), 1);

insert into t_component_type (name, is_use, data_limit, data_group, create_date, creator_id, edit_date, editor_id) values ('广告组', 1, 0, 1, sysdate(), 1, sysdate(), 1);
insert into t_component_type (name, is_use, data_limit, data_group, create_date, creator_id, edit_date, editor_id) values ('小图导航', 1, 4, 2, sysdate(), 1, sysdate(), 1);
insert into t_component_type (name, is_use, data_limit, data_group, create_date, creator_id, edit_date, editor_id) values ('文字导航', 1, 0, 2, sysdate(), 1, sysdate(), 1);
insert into t_component_type (name, is_use, data_limit, data_group, create_date, creator_id, edit_date, editor_id) values ('书籍推荐', 1, 0, 1, sysdate(), 1, sysdate(), 1);
insert into t_component_type (name, is_use, data_limit, data_group, create_date, creator_id, edit_date, editor_id) values ('小图频道推荐', 1, 0, 1, sysdate(), 1, sysdate(), 1);
insert into t_component_type (name, is_use, data_limit, data_group, create_date, creator_id, edit_date, editor_id) values ('大图频道推荐', 1, 0, 1, sysdate(), 1, sysdate(), 1);
insert into t_component_type (name, is_use, data_limit, data_group, create_date, creator_id, edit_date, editor_id) values ('通栏单广告', 1, 0, 1, sysdate(), 1, sysdate(), 1);
insert into t_component_type (name, is_use, data_limit, data_group, create_date, creator_id, edit_date, editor_id) values ('通栏双广告', 1, 2, 1, sysdate(), 1, sysdate(), 1);
insert into t_component_type (name, is_use, data_limit, data_group, create_date, creator_id, edit_date, editor_id) values ('分类组件', 1, 0, 1, sysdate(), 1, sysdate(), 1);
insert into t_component_type (name, is_use, data_limit, data_group, create_date, creator_id, edit_date, editor_id) values ('搜索组件', 1, 0, 1, sysdate(), 1, sysdate(), 1);
insert into t_component_type (name, is_use, data_limit, data_group, create_date, creator_id, edit_date, editor_id) values ('大图导航', 1, 0, 1, sysdate(), 1, sysdate(), 1);
insert into t_component_type (name, is_use, data_limit, data_group, create_date, creator_id, edit_date, editor_id) values ('榜单组件', 1, 6, 1, sysdate(), 1, sysdate(), 1);

insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('出版', 0, 0, 1, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('原创', 0, 0, 1, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('内容时空', 0, 0, 3, 1, 0,'1,1', sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('内容类型', 0, 0, 3, 1, 0,'1,1', sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('内容风格', 0, 0, 3, 1, 0,'1,1', sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('内容情节补充', 0, 0, 4, 1, 0,'1,2', sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('角色特征', 0, 0, 4, 1, 0,'1,2', sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('角色身份', 0, 0, 4, 1, 0,'1,2', sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('角色关系', 0, 0, 4, 1, 0,'1,2', sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('内容背景补充', 0, 0, 4, 1, 0, '0,2', sysdate(), 1, sysdate(), 1);
alter table t_tag auto_increment=101;
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('小说 ', 1, 1, 1, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('非小说', 1, 1, 1, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('小说 ', 2, 1, 1, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('非小说', 2, 1, 1, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('男频', 0, 1, 2, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('女频', 0, 1, 2, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('综合', 0, 1, 2, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('洪荒', 3, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('历史', 3, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('现代', 3, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('架空', 3, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('未来', 3, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('爱情婚姻', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('青春校园', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('武侠', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('仙侠', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('奇幻', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('玄幻', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('异能', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('末世', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('异世大陆', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('机甲战舰', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('军旅生涯', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('战争幻想', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('谍战', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('竞技', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('盗墓', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('网游', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('科幻', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('商场', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('官场', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('职场', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('都市生活', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('娱乐风云', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('乡土百态', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('恐怖', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('灵异', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('悬疑', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('经典名著', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('成功励志', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('处世哲学', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('演讲口才', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('两性关系', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('时尚生活', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('运程占卜', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('健康养生', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('旅游地理', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('笑话/幽', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('烹饪美食', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('美容纤体', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('家居装饰', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('运动休闲', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('传记', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('经济管理', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('文学艺术', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('散文随笔', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('社科', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('少儿读物', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('孕产育儿', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('教辅教材', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('科技', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('剧本', 4, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('纪实', 5, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('严肃', 5, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('通俗', 5, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('正剧', 5, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('热血', 5, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('狗血', 5, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('虐文', 5, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('爽文', 5, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('宠文', 5, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('搞笑', 5, 1, 3, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('重生', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('穿越', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('反穿越', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('宫斗', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('宅斗', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('技术流', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('升级流', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('励志', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('复仇', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('位面', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('权谋', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('丹药法宝', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('种田文', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('失忆', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('绝症', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('女扮男装', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('性别转换', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('创业', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('养成', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('转世', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('召唤文', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('军婚', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('种马文', 6, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('豪门', 7, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('废柴', 7, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('女强', 7, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('女尊', 7, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('扮猪吃虎', 7, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('傲娇', 7, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('纨绔', 7, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('腹黑', 7, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('小人物', 7, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('精英', 7, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('妖孽', 7, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('风流', 7, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('铁血', 7, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('冷血', 7, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('小女人', 7, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('专情', 7, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('强势', 7, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('冰山', 7, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('黑客', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('明星', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('总裁', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('高干', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('杀手', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('特工', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('特种兵', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('医生', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('宅男', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('老师', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('白领', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('学生', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('嫡女', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('庶女', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('弃妇', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('秘书', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('校花', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('校草', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('雇佣兵', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('剩女', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('保镖', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('王妃', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('女佣', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('妖精', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('血族', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('皇帝', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('皇后', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('将军', 8, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('初恋', 9, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('暗恋', 9, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('苦恋', 9, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('一见钟情', 9, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('破镜重圆', 9, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('青梅竹马', 9, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('欢喜冤家', 9, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('阴差阳错', 9, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('春风一度', 9, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('强取豪夺', 9, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('不伦之恋', 9, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('暧昧', 9, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('从一而终', 9, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('NP/一对多', 9, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('女追男', 9, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('艳遇', 9, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('蜀山', 10, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('斗气世界', 10, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('ABO', 10, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('红楼梦', 10, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('三国演义', 10, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('水浒传', 10, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);
insert into t_tag (name, parent_id, is_leaf, type_id, is_use, book_count, scope, create_date, creator_id, edit_date, editor_id) values ('西游记', 10, 1, 4, 1, 0, null, sysdate(), 1, sysdate(), 1);

INSERT INTO t_client_tab(name,order_id,url,create_date,creator_id,edit_date,editor_id,status) VALUES ( '首首', '1', 'http://front.duoquyuedu.com', sysdate(), '1', sysdate(), '1', 0);
INSERT INTO t_client_tab(name,order_id,url,create_date,creator_id,edit_date,editor_id,status) VALUES ( '分类', '2', 'http://front.duoquyuedu.com/ft/type/show.do', sysdate(), '1', sysdate(), '1', 0);
INSERT INTO t_client_tab(name,order_id,url,create_date,creator_id,edit_date,editor_id,status) VALUES ( '排排', '3', 'http://front.duoquyuedu.com/ft/rank/show.do', sysdate(), '1', sysdate(), '1', 0);
